version: '3.1'

services:


  mosquitto:
    image: eclipse-mosquitto
    restart: "no"
    ports:
      - 1883:1883
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log/

  # db:
  #   image: mysql:5.7
  #   restart: 'no'
  #   environment:
  #     MYSQL_DATABASE: exampledb
  #     MYSQL_USER: exampleuser
  #     MYSQL_PASSWORD: examplepass
  #     MYSQL_RANDOM_ROOT_PASSWORD: '1'
  #   volumes:
  #     - db:/var/lib/mysql

volumes:
  mosquitto-data:
  mosquitto-log:
  # db:
